---
kind: pipeline
name: default

steps:
- name: build
  image: alpine:latest
  commands: 
    - sh build.sh

- name: publish  
  image: plugins/github-release
  when:
    ref:
      include: 
        - refs/tags/release-*
      exclude:
        - refs/tags/**
  settings:
    api_key:
      from_secret: github_token
