---
kind: pipeline
name: default

clone:
  disable: true

steps:
- name: clone recursive
  image: alpine/git
  commands:
    - git clone --recursive --depth=1 ${DRONE_GIT_HTTP_URL} .

- name: build
  image: alpine:3.13
  commands: 
    - sh +x build.sh
- name: publish  
  image: plugins/github-release
  when:
    ref:
      include: 
        - refs/tags/release-*
  settings:
    api_key:
      from_secret: github_token
    files:
      - output/minidlna-static.tar.gz
    when:
      event: tag
