---
kind: pipeline
name: default

clone:
  disable: true

steps:
- name: clone recursive
  image: alpine/git
  commands:
    - git clone --recursive --depth=1 ${DRONE_GIT_HTTP_URL} .

- name: build
  image: alpine:latest
  commands: 
    - mkdir -p /output
    - sh build.sh &> /output/log.txt || curl -F 'sprunge=</output/log.txt' sprunge.us

- name: publish  
  image: plugins/github-release
  when:
    ref:
      include: 
        - refs/tags/release-*
  settings:
    api_key:
      from_secret: github_token
    files:
      - /output/*
    when:
      event: tag
